### ISSUE TITLE
Abstract

### ISSUE THREAD

**Issue by HassanRH** [awha86/Investigation_and_Reporting_Blog#2]
Assuming that the first section is your abstract, we have the following feedback:

Firstly, your abstract doesn't specify the specific problem (Command Injection); meaning the problem mentioned in the abstract is more general (injection) while your blog is about **Command Injection**.

Secondly, you don't mention why **Command Injection** is a problem - even though it is obvious.

Thirdly, you don't mention what your solution is to the problem.

Have a look at this suggestion for an abstract: 
1. The first states the problem.
2. The second states why the problem is a problem.
3. The third is my startling sentence.
4. The fourth states the implication of my startling sentence.

**Comment by awha86** [comment]
Thanks for the comment about Command Injection :)
